export const GET_PIZZAS_REQUEST = 'GET_PIZZAS_REQUEST';
export const GET_PIZZAS_SUCCESS = 'GET_PIZZAS_SUCCESS';
export const GET_PIZZAS_ERROR = 'GET_PIZZAS_ERROR';

export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_ERROR = 'ADD_TO_CART_ERROR';

export  const EMPTY_CART = 'EMPTY_CART';
